version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: "mysql://root:root@localhost/test"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "6603:3306"
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
